### ISSUE TITLE
update-initramfs -u WARNING

### ISSUE THREAD

**Issue by GavinIves** [strongtz/i915-sriov-dkms#110]
CPU:13-12100
The host is PVE and the kernel is 6.2. The virtual machine is ubuntu server 22.04 and the kernel is 6.2. Everything was normal according to the steps, and finally the virtual machine successfully obtained the nuclear display. At present, it seems that everything is normal, but when I executed update-initramfs -u on the virtual machine, the following warning occurred. I've searched the internet and haven't found a solution so far. I wonder if it affects functionality.

```root@production:/lib/firmware/i915# update-initramfs -u
update-initramfs: Generating /boot/initrd.img-6.2.0-32-generic
W: Possible missing firmware /lib/firmware/i915/mtl_gsc_102.0.0.1511.bin for module i915
W: Possible missing firmware /lib/firmware/i915/mtl_huc_8.4.3_gsc.bin for module i915
W: Possible missing firmware /lib/firmware/i915/mtl_guc_70.6.4.bin for module i915
W: Possible missing firmware /lib/firmware/i915/adlp_dmc.bin for module i915
root@production:/lib/firmware/i915# ```

**Comment by GavinIves** [comment]
i find some information
<img width="1013" alt="image" src="https://github.com/strongtz/i915-sriov-dkms/assets/38970877/19706abb-7ab4-4c86-adb2-c9b6903d835f">
maybe just name different??

**Comment by scyto** [comment]
can you  solve with this https://unix.stackexchange.com/questions/556946/possible-missing-firmware-lib-firmware-i915-for-module-i915

**Comment by scyto** [comment]
also try this

```
mkdir firmware
cd firmware
wget -r -nd -e robots=no -A '*.bin' --accept-regex '/plain/' https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915/
sudo mv *.bin /lib/firmware/i915/
sudo update-initramfs -c -k all
```

**Comment by GavinIves** [comment]
its work
but we need rename *.bin

**Comment by GavinIves** [comment]
These missing files must be installed. It will affect emby's hardware transcoding. Although emby will show that hardware transcoding is successfully enabled, its efficiency is very low. For transcoding 4khdr into 1080sdr, there are only 40 frames without installing these files. After that, there are 80 frames.

**Comment by HibernantBear** [comment]
> These missing files must be installed. It will affect emby's hardware transcoding. Although emby will show that hardware transcoding is successfully enabled, its efficiency is very low. For transcoding 4khdr into 1080sdr, there are only 40 frames without installing these files. After that, there are 80 frames.

I have met the same problem as you, I try download these files metioned before, but none of them meet the same name as I missing(these files that I'm missing are all the same name as yours), so could you please tell me how to rename them? and do they really acts fine? thank you very much
