### ISSUE TITLE
Support QSV？

### ISSUE THREAD

**Issue by GavinIves** [strongtz/i915-sriov-dkms#112]
Hello, I want to know if it currently supports qsv. I found that my CPU supports this function, but it disappeared after sriov. If it is not supported currently, will it be supported in the future?

**Comment by MotherOfTheGracchi** [comment]
What software are you using? I tested QSV with fmpeg ("_qsv" encoders) and noticed I need to pass "-low_power 1" for encoder to properly initialize.

**Comment by GavinIves** [comment]
sorry, its support qsv, i configer it error
