### ISSUE TITLE
Unable to install the driver in Void Linux w/ kernel v6.5

### ISSUE THREAD

**Issue by MaZED-UP** [strongtz/i915-sriov-dkms#128]
I have followed the steps in the guide but `dkms` fails building the module for some reason. I can't tell if it's because of the newer kernel version or something else.
```
i915-sriov-dkms on  master [!] 
❯ dkms status
i915-sriov-dkms/test: added

i915-sriov-dkms on  master [!] 
❯ sudo dkms install -m i915-sriov-dkms -v test --force
Sign command: /lib/modules/6.5.12_1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j12 KERNELRELEASE=6.5.12_1 -j12 -C /lib/modules/6.5.12_1/build M=/var/lib/dkms/i915/test/build KVER=6.5.12_1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.5.12_1 (x86_64)
Consult /var/lib/dkms/i915-sriov-dkms/test/build/make.log for more information.
```

Here's how I set it up:
```
i915-sriov-dkms on  master [!] 
❯ head -n 2 dkms.conf 
PACKAGE_NAME="i915"
PACKAGE_VERSION="test"

i915-sriov-dkms on  master [!] 
❯ ll /usr/src/
drwxr-xr-x - root 29 Nov 22:44  i915-sriov-dkms-test
```

**Comment by qiukun39** [comment]
> Thanks for your reply @resiliencer. I'm a bit confused about the second option: Are you suggesting that I should change `xbps-install` kernel sources to Arch's and then install version 6.2?

Dude, I got the same mistake. Did you fix it

**Comment by resiliencer** [comment]
> Thanks for your reply @resiliencer. I'm a bit confused about the second option: Are you suggesting that I should change `xbps-install` kernel sources to Arch's and then install version 6.2?

Hi. Sorry for late answer. I mean that I compiled the DKMS module in the working Arch and then took that Arch kernel and launched Alpine with it. And it works for me. To do this, I added an entry to the grub and copied the folder of the same name as the kernel version from Arch to Alpine into /lib/modules. You can try it with Void Linux or not. As you wish. I am currently using Alpine with kernel from Arch. And it works with no problem.
