### ISSUE TITLE
"device initialization failed" when booting a debian vm

### ISSUE THREAD

**Issue by ltsdw** [strongtz/i915-sriov-dkms#13]
I don't know much about virtualization, even less about sr-iov, since intel 11th gen processors doesn't have support to gvt-g I looked up for an alternative and decided to try this sr-iov thing.

Probably this isn't the place to report this but maybe someone knows something.

![Screenshot-03-11-2022_19-13-23](https://user-images.githubusercontent.com/44977415/199846138-835b8447-641d-4660-a085-f0b2a20714b2.png)
![Screenshot-03-11-2022_19-27-01](https://user-images.githubusercontent.com/44977415/199846271-bd9ad26b-0e3d-403c-848a-509039dac20d.png)

[debian11.xml.txt](https://github.com/strongtz/i915-sriov-dkms/files/9933410/debian11.xml.txt)

**Comment by strongtz** [comment]
Does the VM have dkms module installed?

**Comment by ltsdw** [comment]
> Does the VM have dkms module installed?

not that I'm aware of, only dkms module that I have is the i915-sriov.

all I did was follow the basic qemu vertualization wiki page from arch [QEMU](https://wiki.archlinux.org/title/QEMU), installed the qemu-ui-egl-headless and adapted a xml that I  found on reddit.

didn't install anything on the guest.

**Comment by strongtz** [comment]
you need to install this module in VM as well

**Comment by ltsdw** [comment]
Thank you, I tried compiling the module using dkms on debian, but the building is failing because of some functions not implemented in the kernel headers.

I'll close this issue as I'm not familiar with virtualization, dkms and the problem apparently isn't related to this project.
