### ISSUE TITLE
N100 Unable to virtualize device properly

### ISSUE THREAD

**Issue by Meilinhost** [strongtz/i915-sriov-dkms#130]
I've tried to install it more than 20 times according to the tutorials on the web, but it fails.
I read that 6.2.16-9 has the best support for sriov, so I locked the kernel to 6.2.16-9, compiled, setup, rebooted, and no device.
I don't know what's wrong, I'm running out of ideas.
![123](https://github.com/strongtz/i915-sriov-dkms/assets/3524108/a0f4f5e1-a2b8-44c8-971e-f7d736a360c8)
![80a07422-d038-4271-8ea5-42831129b7a2](https://github.com/strongtz/i915-sriov-dkms/assets/3524108/8d9f46b9-67ac-4805-ad18-2f890d6a2f0a)
![d4af88bf-60e9-4454-9dff-bcf1efd87034](https://github.com/strongtz/i915-sriov-dkms/assets/3524108/f3ca79ba-125c-4ad8-b20f-e72adac1235f)

**Comment by gavinsama** [comment]
me too,I'm so tired!!!

**Comment by Meilinhost** [comment]
> 我也是，好累！！！

A while ago I finished sriov. configuration utilizing the pve_source script, you can try it out

**Comment by Meilinhost** [comment]
> > > me too,I'm so tired!!!
> > 
> > 
> > A while ago I finished sriov. configuration utilizing the pve_source script, you can try it out
> 
> Thank you ！what's your PVE version ？Kernel version？

pve is using the latest version 8.x, the kernel is also updated to the latest, pve version and kernel is not the main problem, but the driver problem, you can go to see the article, the keyword is "pve_source".

**Comment by gavinsama** [comment]
> > > > me too,I'm so tired!!!
> > > 
> > > 
> > > A while ago I finished sriov. configuration utilizing the pve_source script, you can try it out
> > 
> > 
> > Thank you ！what's your PVE version ？Kernel version？
> 
> pve is using the latest version 8.x, the kernel is also updated to the latest, pve version and kernel is not the main problem, but the driver problem, you can go to see the article, the keyword is "pve_source". https://bbs.x86pi.cn/thread?topicId=20

thank you so much~
