### ISSUE TITLE
Build failed on archlinux 6.6.14-1-lts 

### ISSUE THREAD

**Issue by mio-19** [strongtz/i915-sriov-dkms#135]
commit: https://github.com/strongtz/i915-sriov-dkms/commit/ee5795dff11f2796710dda537d3c60b5512c6fcd
(I lost the build log)

**Comment by mio-19** [comment]
[make.log](https://github.com/strongtz/i915-sriov-dkms/files/14081517/make.log)

**Comment by a17t** [comment]
There actually has been a change for function drm_dp_calc_pbn_mode.

**Comment by a17t** [comment]
@mio-19 please try building whats in the linked PR

**Comment by mio-19** [comment]
> @mio-19 please try building whats in the linked PR

It worked
