### ISSUE TITLE
centos内核3.10.0-1160.119.1.el7能否使用驱动

### ISSUE THREAD

**Issue by qewra99** [strongtz/i915-sriov-dkms#185]
如标题，centos支持虚拟化驱动吗，或着有没有可能支持

**Comment by strongtz** [comment]
我倒是很想知道你怎么在这么新的硬件上跑那么旧的内核

**Comment by qewra99** [comment]
因为centos内核真的很老，已经换了ubuntu




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月28日(星期天) 晚上9:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [strongtz/i915-sriov-dkms] centos内核3.10.0-1160.119.1.el7能否使用驱动 (Issue #185)















我倒是很想知道你怎么在这么新的硬件上跑那么旧的内核
