### ISSUE TITLE
pve linux 6.8.12-1-pve compiling issue

### ISSUE THREAD

**Issue by ksong008** [strongtz/i915-sriov-dkms#190]
pve linux 6.8.12-1-pve compiling failed

here is the log
[log.txt](https://github.com/user-attachments/files/16536848/log.txt)

fix with https://github.com/strongtz/i915-sriov-dkms/pull/191.

**Comment by submatrix** [comment]
Same issue and build errors here. Is it possible to force use of an older kernel in the meantime?

**Comment by johntdavis84** [comment]
Yes, absolutely. I’d actually suggest that pinning the Proxmox kernel be added to the project’s instructions as a troubleshooting/stability enhancement option.

I wrote up a process tutorial for kernel pinning here, using the proxmox-boot-tool.
(There were already tutorials, but I needed more details, having never done it before, and decided to write up a more detailed one to share.)

https://forum.proxmox.com/threads/how-to-pin-a-machine-to-proxmox-8-1-or-any-previous-version.145752/￼
How to Pin a Machine to Proxmox 8.1 (or Any Previous Version)?
forum.proxmox.com

**Comment by MacharaStormwing** [comment]
I have the same issue.
I manually downloaded the version proxmox-hernel 6.8.8-4-pve (included proxmox-headers) and then pinned that with 
proxmox-boot-tool kernel pin 6.8.8-4-pve
proxmox-boot-tool refresh

[johntdavis84](https://github.com/johntdavis84): the link has some letters appended that makes the link not work. I removed them and got there manually.

**Comment by johntdavis84** [comment]
Thanks for letting me know. Sorry about that. Not sure what happened; the link works fine from my end. Maybe because I’m logged in?

Does this work? https://forum.proxmox.com/threads/how-to-pin-a-machine-to-proxmox-8-1-or-any-previous-version.145752/

**Comment by freeDom-** [comment]
Also got an error building 6.8.12-1 - reverted back to 6.8.8-4 for now and pinned that.

**Comment by pasbec** [comment]
I've created #191 with a small fix for proxmox-kernel-6.8.12-1-pve.

**Comment by IanRanson** [comment]
Just tested the pull request #191 and seems to be working for me on proxmox-kernel-6.8.12-1-pve, thanks so much @pasbec!

**Comment by scyto** [comment]
I compiled on 6.8.12.-2 today and it compiled just fine
