### ISSUE TITLE
Does this driver (or vfio-pci) support full video passthrough using this i915 driver?

### ISSUE THREAD

**Issue by ewheelerinc** [strongtz/i915-sriov-dkms#216]
We have the following card: VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)

We are able to pass virtual functions into a guest, but what we really want to do is pass the entire video card into the guest so that Windows can control the HDMI output. We have tried using vfio-pci instead of this i915 driver using the following:
```
alias pci:v00008086d00004680sv00001028sd00000C7Bbc03sc00i00 vfio-pci
options vfio-pci ids=8086:4680
```
Windows sees the card but fails to load the driver with error 43.

Note that when we pass just a virtual function into Windows, it sees it and the driver loads fine, but HDMI has no output.

Is it possible to do full video passthrough with this card, with or without the i915 driver?

**Comment by admarty** [comment]
> We have the following card: VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
> 
> We are able to pass virtual functions into a guest, but what we really want to do is pass the entire video card into the guest so that Windows can control the HDMI output. We have tried using vfio-pci instead of this i915 driver using the following:
> 
> ```
> alias pci:v00008086d00004680sv00001028sd00000C7Bbc03sc00i00 vfio-pci
> options vfio-pci ids=8086:4680
> ```
> 
> Windows sees the card but fails to load the driver with error 43.
> 
> Note that when we pass just a virtual function into Windows, it sees it and the driver loads fine, but HDMI has no output.
> 
> Is it possible to do full video passthrough with this card, with or without the i915 driver?

You’re in the wrong repository for this issue. You should check out this one instead:
https://github.com/gangqizai/igd
