### ISSUE TITLE
i7 1260p 支持核显直通吗

### ISSUE THREAD

**Issue by hantianxiaoxue** [strongtz/i915-sriov-dkms#22]
i7 1260p 支持核显直通吗？pve安装win10虚拟机，把核显给win10使用，能实现吗？

**Comment by michael-pptf** [comment]
I can't see why not. The iGPU is the same across the board for Alder Lake/Raptor Lake, but you are using an embedded system, and this DKMS module (or anything SR-IOV) requires correct BIOS implementation to work. 

I don't know what kind of device you are running, but just look into the BIOS to see if you can find an option called "SR-IOV". If it isn't there, chances are it doesn't have the BIOS implementation for it, but there is a slim chance that's enabled by default when you enable both VT-x and VT-d.

Give it a try with a spare SSD to install Proxmox on. The worst thing can happen is you have to swap the SSD again.

**Comment by hantianxiaoxue** [comment]
> I can't see why not. The iGPU is the same across the board for Alder Lake/Raptor Lake, but you are using an embedded system, and this DKMS module (or anything SR-IOV) requires correct BIOS implementation to work.
> 
> I don't know what kind of device you are running, but just look into the BIOS to see if you can find an option called "SR-IOV". If it isn't there, chances are it doesn't have the BIOS implementation for it, but there is a slim chance that's enabled by default when you enable both VT-x and VT-d.
> 
> Give it a try with a spare SSD to install Proxmox on. The worst thing can happen is you have to swap the SSD again.

谢谢，确定N305处理器是可以用的
