### ISSUE TITLE
支持AMD Ryzen 7 5825U吗

### ISSUE THREAD

**Issue by 233cy** [strongtz/i915-sriov-dkms#231]
我操作完毕后没有报错，但重启后核显并没有分割

**Comment by ifwwww** [comment]
amd核显不支持sriov

**Comment by 233cy** [comment]
> amd核显不支持sriov

安装i915成功但是没效果，就是不支持的意思是不。
哎绝望了。amd没其他解决方法了吗。

**Comment by ifwwww** [comment]
只能换intel,amd无解

**Comment by BGzEroll** [comment]
i915是intel的驱动。。。

**Comment by bsdcpp** [comment]
amd集显洗洗睡，从来没有过

**Comment by makazeu** [comment]
你知道 `i915` 的 `i` 是什麽意思嗎？

Do you know why `i915` starts with `i`?
