### ISSUE TITLE
Intel i5-1235U Compatibility with Latest Build?

### ISSUE THREAD

**Issue by johntdavis84** [strongtz/i915-sriov-dkms#233]
Hello,

I'm planning to install Proxmox on a NAS that has an i5-1235U.

I was curious if anyone has the driver working stably on this CPU/iGPU, in either kernel 6.8.x or 6.11.x.

**Comment by DjSni** [comment]
Unfortunately not quite, the latest 6.8.5 does not work at the moment, but the 6.8.4 and all 6.11.x work without problems.

**Comment by johntdavis84** [comment]
Wow. That’s a bit of a surprise, given how rock-solid 6.8.x has been for me on an i7-12700T. Thanks for letting me know.

I’m planning for Plex to be on that machine, so I guess I’ll be using the 6.11 kernel. :)
