### ISSUE TITLE
Do I need an update?

### ISSUE THREAD

**Issue by ShCby** [strongtz/i915-sriov-dkms#35]
I am using the 5.19 kernel and include older dkms modules, do I need to update to Linux 6.1 and use the latest modules? Will there be a performance boost?

CPU:i5-13600k

**Comment by ShCby** [comment]
@strongtz 大佬，抱歉at（跪），想问问有没有必要

**Comment by strongtz** [comment]
如果你现在能够正常使用的话，我觉得没必要更新

**Comment by ShCby** [comment]
好的，谢谢大佬
