### ISSUE TITLE
Framebuffer/virtual display support?

### ISSUE THREAD

**Issue by neeps** [strongtz/i915-sriov-dkms#45]
I've been attempting to start gnome and gdk with iGPU passthrough, but X11 complains about missing framebuffer during bootup.
Anyone know whether there its possible to circumvent or workaround this in any way? I intend to create a headless vm, which can forward GUI application windows over network.

Hypervisor: Ubuntu, VM: Ubuntu

**Comment by sieskei** [comment]
I think it's not possible at the moment because the virtual card has no output like gvt-g and I couldn't attach a virtual monitor to it in Ubuntu.

**Comment by neeps** [comment]
Thank you @sieskei, for confirming that you are unable too. I'll close this issue for now then.

**Comment by FallingSnow** [comment]
Maybe you could use this? https://docs.kernel.org/gpu/vkms.html

**Comment by neeps** [comment]
@FallingSnow Thank you!
That coupled with file permission a=+rw to /dev/dri/renderD128 solved problems i had with hardware acceleration for remote firefox.

**Comment by tristan-k** [comment]
@neeps Can you describe the things you did step by step with the proper commands?

**Comment by neeps** [comment]
Not anymore unfortunately, after a couple of reboots both gnome and sway refuse to work with vkms+Intel gpu

**Comment by neeps** [comment]
If any of you are interested in pursuing such a setup, my setup is complaining about missing  /usr/lib/dri/vkms_dri.so.
waypipe client + server setup, and from hypervisor host this used to work:

waypipe --video=hw,bpf=120000,h264 --remote-node=/dev/dri/renderD128 ssh <IP> env WAYLAND_DISPLAY=wayland-1 MOZ_ENABLE_WAYLAND=1 MOZ_WAYLAND_DRM_DEVICE=/dev/dri/renderD128 MOZ_DRM_DEVICE=/dev/dri/renderD128 MOZ_DISABLE_RDD_SANDBOX=1 firefox --no-profile --new-instance

**Comment by sieskei** [comment]
Hello @neeps,
I'm interested in understanding what you're doing, but everything is very unclear.
Please describe the steps related to VKMS.

I have compiled sr-iov i915 in the host and client, and the virtual video card is available in the guest. What do we do next?

**Comment by FallingSnow** [comment]
> If any of you are interested in pursuing such a setup, my setup is complaining about missing /usr/lib/dri/vkms_dri.so. waypipe client + server setup, and from hypervisor host this used to work:
> 
> waypipe --video=hw,bpf=120000,h264 --remote-node=/dev/dri/renderD128 ssh <IP> env WAYLAND_DISPLAY=wayland-1 MOZ_ENABLE_WAYLAND=1 MOZ_WAYLAND_DRM_DEVICE=/dev/dri/renderD128 MOZ_DRM_DEVICE=/dev/dri/renderD128 MOZ_DISABLE_RDD_SANDBOX=1 firefox --no-profile --new-instance

If you are using qemu, you may want to try virtio gpu with opengl and spice enabled. There is a `/usr/lib/dri/virtio_gpu_dri.so`. You don't need vkms at that point. Then you might be able to run your command.
