### ISSUE TITLE
Pentium® Gold Processor 8505 error

### ISSUE THREAD

**Issue by chenjie4500168** [strongtz/i915-sriov-dkms#49]
root@chenxiaogou:~# dmesg | grep i915
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-6.1.6-1-pve root=/dev/mapper/pve-root ro quiet intel_iommu=on i915.enable_guc=7
[    0.053516] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.1.6-1-pve root=/dev/mapper/pve-root ro quiet intel_iommu=on i915.enable_guc=7
[    3.028179] i915 0000:00:02.0: Running in SR-IOV PF mode
[    3.028505] i915 0000:00:02.0: [drm] VT-d active for gfx access
[    3.028628] i915 0000:00:02.0: vgaarb: deactivate vga console
[    3.028680] i915 0000:00:02.0: [drm] Using Transparent Hugepages
[    3.029107] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    3.030113] mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_component_ops [i915])
[    3.032435] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adlp_dmc_ver2_16.bin (v2.16)
[    3.151168] i915 0000:00:02.0: [drm] *ERROR* Zero GuC log crash dump size!
[    3.151174] i915 0000:00:02.0: [drm] *ERROR* Zero GuC log debug size!
[    3.151517] i915 0000:00:02.0: [drm] GuC error state capture buffer maybe too small: 2097152 < 2163708 (min = 721236)
[    3.153408] i915 0000:00:02.0: [drm] GuC firmware i915/adlp_guc_70.bin version 70.5.1
[    3.153410] i915 0000:00:02.0: [drm] HuC firmware i915/tgl_huc.bin version 7.9.3
[    3.170223] i915 0000:00:02.0: [drm] HuC authenticated
[    3.170490] i915 0000:00:02.0: [drm] GuC submission enabled
[    3.170491] i915 0000:00:02.0: [drm] GuC SLPC enabled
[    3.170788] i915 0000:00:02.0: [drm] GuC RC: enabled
[    3.171524] mei_pxp 0000:00:16.0-fbf6fcf1-96cf-4e2e-a6a6-1bab8cbe36b1: bound 0000:00:02.0 (ops i915_pxp_tee_component_ops [i915])
[    3.171626] i915 0000:00:02.0: [drm] Protected Xe Path (PXP) protected content support initialized
[    3.202324] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 0
[    3.227366] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    3.227462] i915 0000:00:02.0: 7 VFs could be associated with this PF
[    3.230331] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    3.360834] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    3.360943] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    3.830594] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=io+mem
[    3.830662] i915 0000:00:02.1: enabling device (0000 -> 0002)
[    3.830704] i915 0000:00:02.1: Running in SR-IOV VF mode
[    3.831225] i915 0000:00:02.1: GuC interface version 0.1.0.0
[    3.831826] i915 0000:00:02.1: [drm] VT-d active for gfx access
[    3.831843] i915 0000:00:02.1: [drm] Using Transparent Hugepages
[    3.832360] i915 0000:00:02.1: GuC interface version 0.1.0.0
[    3.832581] i915 0000:00:02.1: GuC firmware PRELOADED version 1.0 submission:SR-IOV VF
[    3.832583] i915 0000:00:02.1: HuC firmware PRELOADED
[    3.834064] i915 0000:00:02.1: [drm] Protected Xe Path (PXP) protected content support initialized
[    3.834070] i915 0000:00:02.1: [drm] PMU not supported for this GPU.
[    3.834140] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.1 on minor 1
[    3.834641] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=none,decodes=none:owns=io+mem
[    3.834644] i915 0000:00:02.1: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=none
[    3.834708] i915 0000:00:02.2: enabling device (0000 -> 0002)
[    3.834748] i915 0000:00:02.2: Running in SR-IOV VF mode
[    3.835238] i915 0000:00:02.2: GuC interface version 0.1.0.0
[    3.835509] i915 0000:00:02.2: [drm] VT-d active for gfx access
[    3.835526] i915 0000:00:02.2: [drm] Using Transparent Hugepages
[    3.836033] i915 0000:00:02.2: GuC interface version 0.1.0.0
[    3.836215] i915 0000:00:02.2: GuC firmware PRELOADED version 1.0 submission:SR-IOV VF
[    3.836217] i915 0000:00:02.2: HuC firmware PRELOADED
[    3.837863] i915 0000:00:02.2: [drm] Protected Xe Path (PXP) protected content support initialized
[    3.837867] i915 0000:00:02.2: [drm] PMU not supported for this GPU.
[    3.837921] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.2 on minor 2
[    3.838091] i915 0000:00:02.0: Enabled 2 VFs
[  373.744162] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=none,decodes=none:owns=io+mem
[  373.744167] i915 0000:00:02.2: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=none
[  373.892142] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=none,decodes=io+mem:owns=io+mem
[  375.079633] i915 0000:00:02.0: Disabled 2 VFs

**Comment by michael-pptf** [comment]
log file looks clean, please provide more details as to how you went about using the VFs and the steps to reproduce the problem.
