### ISSUE TITLE
has anyone test passthrough uhd770 ogpu into a guest

### ISSUE THREAD

**Issue by vvhh2002** [strongtz/i915-sriov-dkms#5]
I've tried multiple times and failed

**Comment by skill7899** [comment]
![image](https://user-images.githubusercontent.com/13962272/195746501-72ffb38c-8a64-40c6-8b4a-c2d5e2d651c3.png)
i success

**Comment by Alion548** [comment]
> 

Please help me to test if chrome gpu hardware acceleration can work properly, visit: chrome://gpu, thanks a lot!

**Comment by Alion548** [comment]
@skill7899 

Please help me to test if chrome gpu hardware acceleration can work properly, visit: chrome://gpu, thanks a lot!

**Comment by vvhh2002** [comment]
If the driver can correctly hardware acceleration. You should use rustDesk for testing but not RDP . The right vGPU should be able to virtualize a monitor, as GVT-D does.

**Comment by skill7899** [comment]
> @skill7899
> 
> Please help me to test if chrome gpu hardware acceleration can work properly, visit: chrome://gpu, thanks a lot!

。。i find the driver response code 43 error

**Comment by skill7899** [comment]
success https://github.com/strongtz/i915-sriov-dkms/issues/7

**Comment by michael-pptf** [comment]
> @skill7899
> 
> Please help me to test if chrome gpu hardware acceleration can work properly, visit: chrome://gpu, thanks a lot!

Graphics Feature Status
Canvas: Hardware accelerated
Canvas out-of-process rasterization: Disabled
Direct Rendering Display Compositor: Disabled
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
OpenGL: Enabled
Rasterization: Hardware accelerated
Raw Draw: Disabled
Video Decode: Hardware accelerated
Video Encode: Hardware accelerated
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
WebGPU: Hardware accelerated
