### ISSUE TITLE
Hard blocking on host

### ISSUE THREAD

**Issue by nikolasgkou** [strongtz/i915-sriov-dkms#56]
When VM powers on my host blocks very hard. I can't do any actions every 4-5 seconds, not even mouse movements : 

[ 4701.292835] mmap kvmfr0: 7fe8181f4000-7fe81a1f4000 with size 33554432 offset 0
[ 4701.945728] i915 0000:00:02.0: VF1 FLR
[ 4702.066646] i915 0000:00:02.0: VF1 FLR
[ 4703.217128] virbr0: port 1(vnet0) entered learning state
[ 4705.266055] virbr0: port 1(vnet0) entered forwarding state
[ 4705.266069] virbr0: topology change detected, propagating
[ 4747.377391] i915 0000:00:02.0: [drm] Resetting chip for stopped heartbeat on rcs0
[ 4747.479664] i915 0000:00:02.0: [drm] GuC firmware i915/adlp_guc_70.bin version 70.5.1
[ 4747.479678] i915 0000:00:02.0: [drm] HuC firmware i915/tgl_huc.bin version 7.9.3
[ 4747.480240] i915 0000:00:02.0: [drm] Missing GuC-Err-Cap reglist Class(1):Compute(4)!
[ 4747.480247] i915 0000:00:02.0: [drm] Missing GuC-Err-Cap reglist Instance(2):Compute(4)!
[ 4747.496247] i915 0000:00:02.0: [drm] HuC authenticated
[ 4747.497136] i915 0000:00:02.0: [drm] GuC submission enabled
[ 4747.497142] i915 0000:00:02.0: [drm] GuC SLPC enabled
[ 4747.741365] i915 0000:00:02.2: [drm] *ERROR* mmio request 0x508: failure a/0
[ 4747.741372] i915 0000:00:02.2: Unsuccessful self-config (-ENXIO) key 0x906 value 0x21c24800
[ 4747.741375] i915 0000:00:02.2: CT: Failed to register RECV buffer (-ENXIO)
[ 4747.741377] i915 0000:00:02.2: CT: Failed to enable CTB (-ENXIO)
[ 4747.746479] i915 0000:00:02.3: [drm] *ERROR* mmio request 0x508: failure a/0
[ 4747.746485] i915 0000:00:02.3: Unsuccessful self-config (-ENXIO) key 0x906 value 0x4157e800
[ 4747.746488] i915 0000:00:02.3: CT: Failed to register RECV buffer (-ENXIO)
[ 4747.746489] i915 0000:00:02.3: CT: Failed to enable CTB (-ENXIO)
[ 4747.751014] i915 0000:00:02.4: [drm] *ERROR* mmio request 0x508: failure a/0
[ 4747.751021] i915 0000:00:02.4: Unsuccessful self-config (-ENXIO) key 0x906 value 0x60ed8800
[ 4747.751023] i915 0000:00:02.4: CT: Failed to register RECV buffer (-ENXIO)
[ 4747.751025] i915 0000:00:02.4: CT: Failed to enable CTB (-ENXIO)
[ 4747.755092] i915 0000:00:02.5: [drm] *ERROR* mmio request 0x508: failure a/0
[ 4747.755104] i915 0000:00:02.5: Unsuccessful self-config (-ENXIO) key 0x906 value 0x80832800
[ 4747.755107] i915 0000:00:02.5: CT: Failed to register RECV buffer (-ENXIO)
[ 4747.755109] i915 0000:00:02.5: CT: Failed to enable CTB (-ENXIO)
[ 4747.759037] i915 0000:00:02.6: [drm] *ERROR* mmio request 0x508: failure a/0
[ 4747.759042] i915 0000:00:02.6: Unsuccessful self-config (-ENXIO) key 0x906 value 0xa018c800
[ 4747.759044] i915 0000:00:02.6: CT: Failed to register RECV buffer (-ENXIO)
[ 4747.759045] i915 0000:00:02.6: CT: Failed to enable CTB (-ENXIO)
[ 4747.763224] i915 0000:00:02.7: [drm] *ERROR* mmio request 0x508: failure a/0
[ 4747.763230] i915 0000:00:02.7: Unsuccessful self-config (-ENXIO) key 0x906 value 0xbfae6800
[ 4747.763233] i915 0000:00:02.7: CT: Failed to register RECV buffer (-ENXIO)
[ 4747.763235] i915 0000:00:02.7: CT: Failed to enable CTB (-ENXIO)
[ 4764.784742] Asynchronous wait on fence 0000:00:02.0:gnome-shell[2767]:af8c timed out (hint:intel_atomic_commit_ready [i915])
[ 4764.785074] Asynchronous wait on fence 0000:00:02.0:gnome-shell[2767]:af8c timed out (hint:intel_atomic_commit_ready [i915])
[ 4768.369270] i915 0000:00:02.0: [drm] Resetting chip for stopped heartbeat on rcs0
[ 4768.369742] i915 0000:00:02.0: [drm] GuC firmware i915/adlp_guc_70.bin version 70.5.1
[ 4768.369752] i915 0000:00:02.0: [drm] HuC firmware i915/tgl_huc.bin version 7.9.3
[ 4768.370350] i915 0000:00:02.0: [drm] Missing GuC-Err-Cap reglist Class(1):Compute(4)!
[ 4768.370359] i915 0000:00:02.0: [drm] Missing GuC-Err-Cap reglist Instance(2):Compute(4)!
[ 4768.387533] i915 0000:00:02.0: [drm] HuC authenticated
[ 4768.388527] i915 0000:00:02.0: [drm] GuC submission enabled
[ 4768.388535] i915 0000:00:02.0: [drm] GuC SLPC enabled
[ 4773.897579] virbr0: port 1(vnet0) entered disabled state
[ 4773.898975] device vnet0 left promiscuous mode
[ 4773.898995] virbr0: port 1(vnet0) entered disabled state
[ 4773.926665] i915 0000:00:02.0: VF1 FLR
[ 4774.288110] vfio-pci 0000:00:02.1: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=none
[ 4774.288912] i915 0000:00:02.1: Running in SR-IOV VF mode
[ 4774.289156] i915 0000:00:02.1: GuC interface version 0.1.0.0
[ 4774.290388] i915 0000:00:02.1: [drm] VT-d active for gfx access
[ 4774.290429] i915 0000:00:02.1: [drm] Using Transparent Hugepages
[ 4774.291070] i915 0000:00:02.1: GuC interface version 0.1.0.0
[ 4774.291457] i915 0000:00:02.1: GuC firmware PRELOADED version 1.0 submission:SR-IOV VF
[ 4774.291460] i915 0000:00:02.1: HuC firmware PRELOADED
[ 4774.294889] i915 0000:00:02.1: [drm] Protected Xe Path (PXP) protected content support initialized
[ 4774.294900] i915 0000:00:02.1: [drm] PMU not supported for this GPU.
[ 4774.295341] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.1 on minor 8

**Comment by michael-pptf** [comment]
Are you using the iGPU as your main display output in your host?

If so, that would not work. The host will use the physical function (PF) and it will not correctly allocate resource if you also have a virtual function (VF) on.

**Comment by nikolasgkou** [comment]
I see, yes, I do use PF as the main display output in the host.
It sometimes works : 
[   69.881612] virbr0: port 1(vnet0) entered blocking state
[   69.881622] virbr0: port 1(vnet0) entered listening state
[   70.212810] mmap kvmfr0: 7f293fdff000-7f2943dff000 with size 67108864 offset 0
[   70.830243] i915 0000:00:02.0: VF1 FLR
[   70.943285] i915 0000:00:02.0: VF1 FLR
[   71.907486] virbr0: port 1(vnet0) entered learning state
[   73.956453] virbr0: port 1(vnet0) entered forwarding state
[   73.956467] virbr0: topology change detected, propagating
[   99.357189] x86/split lock detection: #AC: CPU 2/KVM/5086 took a split_lock trap at address: 0x74989d60
[  107.788446] x86/split lock detection: #AC: CPU 1/KVM/5085 took a split_lock trap at address: 0x74989d60
[  110.967847] x86/split lock detection: #AC: CPU 0/KVM/5084 took a split_lock trap at address: 0x74989d2d
[  266.247017] x86/split lock detection: #AC: CPU 3/KVM/5087 took a split_lock trap at address: 0x74989d2d

The current state of the system is nearly on 0 load. I guess it's not conflicting yet? 
Do you know if it's possible to use the VF for the host? I wonder how the display outputs would work in that case. They seem to be bound to the PF.
