### ISSUE TITLE
Suggestion: Hint to the i915-sriov-dkms-git package in README.md

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [strongtz/i915-sriov-dkms#6]
As the AUR package `i915-sriov-dkms-git` is provided by @strongtz himself, I suggest that in README.md's installation instructions installing of `i915-sriov-dkms-git` is mentioned/recommended there too.

**Comment by sshaikh** [comment]
It would be useful to have some guidance on how to use this:

I've built and installed the package but apart from copying files to /usr/src/i915-sriov-dkms-5.15.71 it doesn't seem to build anything?

```
❯ uname -a
Linux office 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64 GNU/Linux
❯ cd /usr/src/i915-sriov-dkms-5.15.71/
❯ sudo dkms install -m i915-sriov-dkms -v 6.1 --force
Sign command: /usr/lib/modules/6.9.3-arch1-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Error! Could not find module source directory.
Directory: /usr/src/i915-sriov-dkms-6.1 does not exist.
```

Are we supposed to update the version in the PKGBUILD ourselves? Why is the package version set to a kernel anyway? The PKGBUILD should pick it up from the system no?
