### ISSUE TITLE
Ubuntu 2304 w/ 6.2 kernel VM Guest not working

### ISSUE THREAD

**Issue by gzbenson** [strongtz/i915-sriov-dkms#68]
# dmesg | grep drm
[    0.928446] ACPI: bus type drm_connector registered
[    1.327450] bochs-drm 0000:00:01.0: vgaarb: deactivate vga console
[    1.327507] [drm] Found bochs VGA, ID 0xb0c5.
[    1.327509] [drm] Framebuffer size 16384 kB @ 0xc0000000, mmio @ 0xc304b000.
[    1.328272] [drm] Found EDID data blob.
[    1.331086] [drm] Initialized bochs-drm 1.0.0 20130925 for 0000:00:01.0 on minor 0
[    1.331750] fbcon: bochs-drmdrmfb (fb0) is primary device
[    1.536208] bochs-drm 0000:00:01.0: [drm] fb0: bochs-drmdrmfb frame buffer device
[    2.158088] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    2.158103] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    2.758843] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    2.758854] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    2.759025] i915 0000:01:00.0: drm_WARN_ON(s_en != 0x1)
[    2.759036] WARNING: CPU: 2 PID: 118 at drivers/gpu/drm/i915/gt/intel_sseu.c:278 gen12_sseu_info_init+0x185/0x190 [i915]
[    2.759130] Modules linked in: i915(+) drm_buddy i2c_algo_bit hid_generic drm_display_helper bochs(+) crct10dif_pclmul cec crc32_pclmul drm_vram_helper drm_ttm_helper rc_core ttm polyval_clmulni usbhid drm_kms_helper polyval_generic ghash_clmulni_intel syscopyarea sha512_ssse3 aesni_intel sysfillrect i2c_i801 sysimgblt hid crypto_simd cryptd i2c_smbus psmouse ahci virtio_net libahci net_failover lpc_ich virtio_scsi failover drm video wmi
[    2.761927]  ? drm_privacy_screen_get+0x16d/0x190 [drm]
[    3.369375] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    3.369552] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    3.970445] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    3.970638] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    4.571572] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    4.571763] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    4.572112] i915 0000:01:00.0: [drm] L3 bank mask is all zero!
[    5.172798] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    5.173002] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    5.774003] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[    5.774221] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[    6.379333] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    6.379572] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    6.980534] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    6.980766] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    7.581768] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    7.581997] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    8.182933] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    8.183181] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    8.784145] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[    8.784401] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[    9.385373] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[    9.385635] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[    9.986612] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[    9.986877] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   10.587848] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   10.588129] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   11.189130] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   11.189412] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   11.790414] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   11.790709] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   12.391743] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   12.392036] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   12.993029] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   12.993338] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   13.594363] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   13.594710] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   14.195779] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   14.196110] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   14.797157] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   14.797486] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   15.398525] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   15.398881] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   15.999926] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   16.000253] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   16.601294] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   16.601616] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   17.202639] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   17.202996] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   17.204190] i915 0000:01:00.0: [drm] *ERROR* rcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.205112] i915 0000:01:00.0: [drm] *ERROR* rcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.206033] i915 0000:01:00.0: [drm] *ERROR* bcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.209004] i915 0000:01:00.0: [drm] *ERROR* rcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.209917] i915 0000:01:00.0: [drm] *ERROR* bcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.812806] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   17.813121] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   18.414160] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   18.414478] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   19.015531] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   19.015865] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   19.616895] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   19.617216] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   20.218250] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   20.218565] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   20.819615] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   20.819936] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   21.420971] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   21.421285] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   22.022320] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   22.022638] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   22.023135] i915 0000:01:00.0: [drm] *ERROR* Failed to map the ggtt page table
[   23.010505] systemd[1]: Starting modprobe@drm.service - Load Kernel Module drm...
[   23.039375] systemd[1]: modprobe@drm.service: Deactivated successfully.
[   23.039679] systemd[1]: Finished modprobe@drm.service - Load Kernel Module drm.
root@ubuntu2304apps:~# dmesg | grep i915
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-6.2.0-20-generic root=/dev/mapper/ubuntu--vg-ubuntu--lv ro i915.enable_guc=3
[    0.013252] Kernel command line: BOOT_IMAGE=/vmlinuz-6.2.0-20-generic root=/dev/mapper/ubuntu--vg-ubuntu--lv ro i915.enable_guc=3
[    2.158088] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    2.158103] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    2.758843] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    2.758854] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    2.759025] i915 0000:01:00.0: drm_WARN_ON(s_en != 0x1)
[    2.759036] WARNING: CPU: 2 PID: 118 at drivers/gpu/drm/i915/gt/intel_sseu.c:278 gen12_sseu_info_init+0x185/0x190 [i915]
[    2.759130] Modules linked in: i915(+) drm_buddy i2c_algo_bit hid_generic drm_display_helper bochs(+) crct10dif_pclmul cec crc32_pclmul drm_vram_helper drm_ttm_helper rc_core ttm polyval_clmulni usbhid drm_kms_helper polyval_generic ghash_clmulni_intel syscopyarea sha512_ssse3 aesni_intel sysfillrect i2c_i801 sysimgblt hid crypto_simd cryptd i2c_smbus psmouse ahci virtio_net libahci net_failover lpc_ich virtio_scsi failover drm video wmi
[    2.759180] RIP: 0010:gen12_sseu_info_init+0x185/0x190 [i915]
[    2.760428]  ? intel_uncore_forcewake_for_reg+0x4a/0x110 [i915]
[    2.760687]  intel_sseu_info_init+0x69/0x2b0 [i915]
[    2.760950]  intel_gt_init_mmio+0x23/0x40 [i915]
[    2.761201]  i915_driver_mmio_probe+0x129/0x410 [i915]
[    2.761439]  ? intel_gt_probe_all+0x91/0x2e0 [i915]
[    2.761688]  i915_driver_probe+0xe1/0x420 [i915]
[    2.762311]  i915_pci_probe+0xac/0x1b0 [i915]
[    2.764928]  i915_pci_register_driver+0x23/0x30 [i915]
[    2.765139]  i915_init+0x34/0x120 [i915]
[    2.765353]  ? __pfx_init_module+0x10/0x10 [i915]
[    3.369375] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    3.369552] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    3.970445] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    3.970638] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    4.571572] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    4.571763] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    4.572112] i915 0000:01:00.0: [drm] L3 bank mask is all zero!
[    5.172798] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    5.173002] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    5.774003] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[    5.774221] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[    6.379333] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    6.379572] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    6.980534] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    6.980766] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    7.581768] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    7.581997] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    8.182933] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[    8.183181] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[    8.784145] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[    8.784401] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[    9.385373] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[    9.385635] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[    9.986612] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[    9.986877] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   10.587848] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   10.588129] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   11.189130] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   11.189412] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   11.790414] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   11.790709] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   12.391743] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   12.392036] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   12.993029] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   12.993338] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   13.594363] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   13.594710] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   14.195779] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   14.196110] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   14.797157] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   14.797486] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   15.398525] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   15.398881] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   15.999926] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   16.000253] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   16.601294] i915 0000:01:00.0: [drm] *ERROR* render: timed out waiting for forcewake ack to clear.
[   16.601616] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x267/0x2e0 [i915]
[   17.202639] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   17.202996] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   17.204190] i915 0000:01:00.0: [drm] *ERROR* rcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.205112] i915 0000:01:00.0: [drm] *ERROR* rcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.206033] i915 0000:01:00.0: [drm] *ERROR* bcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.209004] i915 0000:01:00.0: [drm] *ERROR* rcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.209917] i915 0000:01:00.0: [drm] *ERROR* bcs'0 reset request timed out: {request: 00000004, RESET_CTL: ffffffff}
[   17.812806] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   17.813121] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   18.414160] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   18.414478] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   19.015531] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   19.015865] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   19.616895] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   19.617216] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   20.218250] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   20.218565] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   20.819615] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   20.819936] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   21.420971] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   21.421285] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   22.022320] i915 0000:01:00.0: [drm] *ERROR* gt: timed out waiting for forcewake ack request.
[   22.022638] i915 0000:01:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x228/0x2e0 [i915]
[   22.023135] i915 0000:01:00.0: [drm] *ERROR* Failed to map the ggtt page table
[   22.131228] i915 0000:01:00.0: Device initialization failed (-12)
[   22.134806] i915: probe of 0000:01:00.0 failed with error -12

**Comment by gzbenson** [comment]
~# lspci -vs 01:00.0
01:00.0 VGA compatible controller: Intel Corporation Alder Lake-S GT1 [UHD Graphics 730] (rev 0c) (prog-if 00 [VGA controller])
        Physical Slot: 0
        Flags: fast devsel
        Memory at c1000000 (64-bit, non-prefetchable) [size=16M]
        Memory at 7000000000 (64-bit, prefetchable) [size=512M]
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [ac] MSI: Enable- Count=1/1 Maskable+ 64bit-
        Kernel modules: i915

**Comment by kugel-** [comment]
What did you do? I have the same issue on a Debian guest.
