### ISSUE TITLE
Is Xen supported?

### ISSUE THREAD

**Issue by fybmain** [strongtz/i915-sriov-dkms#93]
The README document of this driver illustrates the progress of installing it in PVE (which uses KVM). I'd like to figure out whether this project is also available in Xen, as I plan to run Xen on my home server, while I also want to share the ability of parallel computation provided by my iGPU across several VMs.
Xen is a type-I hypervisor which runs below the Linux kernel (which might be a reason why the driver code needs to be modified). Have there been any existing reports about whether it supports Xen or not?

**Comment by craschnet** [comment]
I don't anyone has tried. Assuming Xen can use IOMMU groups for PCI passthrough, it should work, but it would be non-production support. So I'd only try on a test machine and expect limited help.
